# Generated by Django 5.2.1 on 2025-05-19 13:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0002_rename_borrowings_borrowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('session_url', models.URLField(max_length=500)),
                ('money_to_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], default='PAYMENT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowings.borrowing')),
            ],
        ),
    ]
